### ISSUE TITLE
这里有个URL的问题

### ISSUE THREAD

**Issue by sansui-orz** [blackmatch/pornhub-downloader#1]
downloader.js
import urlModule from 'url';
const URL = urlModule.URL;
let myUrl = new URL(url);
let pathName = myUrl.pathname;

改成
import urlModule from 'url';
// const URL = urlModule.URL;
// let myUrl = new URL(url);
let pathName = urlModule.parse(url).pathname;
就ok啦

**Comment by blackmatch** [comment]
@sansui-orz 我写的是有点啰嗦了。因为一开始我写了个全局的url对象，然后导入url模块的时候冲突了，我就随意换了个名字，后来全局的url对象移除了，这里也忘记改了。感谢提醒，下次有时间我改一下。
