### ISSUE TITLE
报错了  不知道是什么原因

### ISSUE THREAD

**Issue by nanzm** [blackmatch/pornhub-downloader#10]
![image](https://user-images.githubusercontent.com/12454813/38464144-08b04eac-3b3b-11e8-95bb-653cdb539d12.png)

**Comment by blackmatch** [comment]
网络问题，目前无解，因为用了代理。

**Comment by blackmatch** [comment]
本项目不再维护，关闭issue。请查看[readme说明](https://github.com/blackmatch/pornhub-downloader)。
