### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by CZZ502** [blackmatch/pornhub-downloader#11]
![aaa](https://user-images.githubusercontent.com/16065865/42379242-a8566cea-815c-11e8-9c79-9d3070f9944a.png)

用VPN 设置了config.json

**Comment by akbarxie** [comment]
同问

**Comment by blackmatch** [comment]
本项目不再维护，关闭issue。请查看[readme说明](https://github.com/blackmatch/pornhub-downloader)。
