### ISSUE TITLE
是否可以下载特定页面

### ISSUE THREAD

**Issue by now163** [blackmatch/pornhub-downloader#6]
例如：
1、favorite页面
https://www.pornhub.com/users/now163/videos/favorites
2、public页面
https://www.pornhub.com/users/cutiegingerrussian/videos/public

**Comment by blackmatch** [comment]
目前没有这个功能，有时间的话考虑加一个。

**Comment by blackmatch** [comment]
@now163 使用最新版本，配置`src/config.json`中的`pathname`，如：你的favorite界面，把`pathname`配置成`/users/now163/videos/favorites`即可。
