### ISSUE TITLE
请教一个问题：为什么要下载下来？

### ISSUE THREAD

**Issue by medmin** [blackmatch/pornhub-downloader#8]
直接网上看，不是随时可以看么

**Comment by blackmatch** [comment]
@medmin 单纯地想通过Node和终端实现下载文件。其他原因嘛，主要是因为那个网站即使用了科学上网，网速也不快，因为我习惯快进 😄

**Comment by blackmatch** [comment]
@medmin 学习是第一，娱乐其次。issue先关了哈。有问题再提issue。
