### ISSUE TITLE
npm start 

### ISSUE THREAD

**Issue by domainvip** [blackmatch/pornhub-downloader#9]
> pornhub-downloader@2.2.1 start /root/avgle/pornhub-downloader
> node ./src

/root/avgle/pornhub-downloader/src/index.js:5
const run = async () => {
                  ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Linux 3.10.0-693.21.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! pornhub-downloader@2.2.1 start: `node ./src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pornhub-downloader@2.2.1 start script 'node ./src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pornhub-downloader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pornhub-downloader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pornhub-downloader
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/avgle/pornhub-downloader/npm-debug.log

**Comment by blackmatch** [comment]
you need to upgrade your node version.
